### ISSUE TITLE
I can't execute it.

### ISSUE THREAD

**Issue by BrennerPV** [Galster2010/GameSettingsUnlocker#4]
I've been trying to disable this mod for weeks but it's not working. When I try to execute it, it says there are missing dlls. I got those dlls and put it together with the mod and tried again, but now it gives me another error (0xc000007b). 

(2 days later): I managed to disable it deleting all of my among us files, but I still can't execute it to install it again. Is there any way I can do that manually?

Ps: I had installed this mod a week before I tried to disable and it was working perfectly, I don't know what went wrong.

**Comment by Galster-dev** [comment]
What version do you use? What OS, game platform?

**Comment by BrennerPV** [comment]
I used the static version the first time, I tried runtime but it has the same problem. Windows and Steam.

**Comment by Galster-dev** [comment]
Well, can you explain the problem better? What does console output and what's wrong?

**Comment by BrennerPV** [comment]
I would print it, but it would all be in portuguese, so i'll just write it.

When I open the .exe it shows that vcruntime140.dll and msvcp140.dll are missing so it won't work.

If I put these two dlls in the same folder with the .exe, it shows another message, that it could not be inicialized correctly because of error (0xc000007b).

both times I just click OK and the the application closes

First time I downloaded, I simply open the exe and it worked. Second time I had this error.

**Comment by Galster-dev** [comment]
Try installing VC Redist 2019 (both x86 and x64)

**Comment by BrennerPV** [comment]
It actually worked, thank you so much!!! I really love this mod, I was sad thinking that I couldn't use it anymore.
