### ISSUE TITLE
Best way for linux?

### ISSUE THREAD

**Issue by 1337god** [Galster2010/GameSettingsUnlocker#6]

**Comment by Galster-dev** [comment]
I'm not a linux user (yet), but can't you just use wine? It should work. If not, use BepInEx version with BepInEx modloader

**Comment by 1337god** [comment]
> I'm not a linux user (yet), but can't you just use wine? It should work. If not, use BepInEx version with BepInEx modloader

I'm using Proton (Steam), but I will try with the BepInEx

**Comment by Galster-dev** [comment]
just a tip 
![image](https://user-images.githubusercontent.com/46283010/112182141-14b88580-8c0e-11eb-860d-4bc01f5dafae.png)

**Comment by Galster-dev** [comment]
@1337god, is it working? If yes, close the issue please.
